# .github/workflows/shelter_cats_report.yml
name: Shelter Cats Report

on:
  schedule:
    - cron: '0 15 * * 1' # Runs every Monday at 3pm UTC
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run report script
        env:
          PETFINDER_KEY: ${{ secrets.PETFINDER_KEY }}
          PETFINDER_SECRET: ${{ secrets.PETFINDER_SECRET }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        run: python shelter_cats_report.py